In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel
from scipy.spatial.distance import cosine
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
metadata1 = np.genfromtxt('metadata1.csv', delimiter=',')
metadata2 = np.genfromtxt('metadata2.csv', delimiter=',')
input_data = [1,1,0,1,1,1,0,1,1,0,1,0,0,0,0,0,0,0,0]

In [3]:
print(metadata1)

[[nan  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [20.  1.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [21.  0.  0.  0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [22.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [23.  0.  0.  0.  1.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [24.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [25.  0.  0.  0.  1.  1.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [26.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  1.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [27.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [28.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [29.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.
   0.  0.]
 [30.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.

In [4]:
print(metadata2)

[[nan 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32.]
 [33.  1.  1.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [34.  1.  1.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [35.  1.  1.  1.  0.  0.  1.  1.  0.  0.  1.  0.  0.  0.]
 [36.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.]
 [37.  0.  0.  1.  0.  0.  1.  0.  0.  1.  0.  0.  0.  1.]]


In [5]:
print(input_data)

[1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
